### PR TITLE
Replace MPI_LB/UB usage with MPI_Type_create_resized

### PR DESCRIPTION
**Pull request by hjelmn**
The MPI_LB and MPI_UB markers were removed from the MPI standard in
MPI-3.0. Their use was deprecated in MPI-2.

Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>

### CODE REVIEW

**Comment by hjelmn** [comment]
This goes one step further than #5 and removes the MPI_LB/UB usage.

**Comment by gpaulsen** [comment]
@VinnitskiV Is there a schedule for when this might get into IMB?
Open MPI v4.0.0 is scheduled to release September 17th, and it would be nice if it could compile and run IMB without enabling the old MPI 1 removed APIs.

**Comment by VinnitskiV** [comment]
@gpaulsen 
In Q3 2018

**Comment by gpaulsen** [comment]
I verified this branch builds and runs okay with Open MPI v4.0.0rc1 with default configure options (i.e. without --enable-mpi1-compatibility)

**Pull request closed without merging**
